
CC = clang
CFLAGS_STD = -std=c11
CFLAGS_DEBUG = -g -O0
CFLAGS_RELESE = -O2
CFLAGS_WARNING = -Wall -Wextra -Werror
CFLAGS = $(CFLAGS_STD) $(CFLAGS_DEBUG) $(CFLAGS_WARNING)

.PHONY: all
all: minfind

minfind: minfind.o

